LOAD DATA LOCAL INFILE 'parsed/Users.dat' INTO TABLE Users FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE 'parsed/Bids.dat' INTO TABLE Bids FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE 'parsed/Items.dat' INTO TABLE Items FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE 'parsed/ItemCategory.dat' INTO TABLE ItemCategory FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
LOAD DATA LOCAL INFILE 'parsed/SellerRating.dat' INTO TABLE SellerRating FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
